export const AUTH_LOGIN_LOADING = 'AUTH_LOGIN_LOADING';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';

export const AUTH_REGISTER_LOADING = 'AUTH_REGISTER_LOADING';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

export const AUTH_GET_USER_LOADING = 'AUTH_GET_USER__LOADING';
export const AUTH_GET_USER_SUCCESS = 'AUTH_GET_USER_SUCCESS';
export const AUTH_GET_USER_FAIL = 'AUTH_GET_USER_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
